apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "walletconnect.labels" .  | indent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: {{ .Values.ingressClassName | default "nginx" }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Release.Name }}.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ .Release.Name }}
            port: 5000
