apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odis-signer-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end }}
  tls:
  - secretName: {{ .Release.Namespace }}-web-tls
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "name" . }}
            port: 3000