apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komenci-onboarding-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end }}
  tls:
  - hosts:
    - {{ .Values.onboarding.publicHostname }}
    secretName: {{ .Release.Namespace }}-web-tls
  rules:
  - host: {{ .Values.onboarding.publicHostname }}
    http:
      paths:
      - path: /rewards
        backend:
          service:
            name: {{ .Release.Namespace }}-rewards
            port: 3000
      - path: /
        backend:
          service:
            name: {{ .Release.Namespace }}-onboarding
            port: 3000
